from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
INTERIM_DATA_DIR = DATA_DIR / "interim"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
EXTERNAL_DATA_DIR = DATA_DIR / "external"

ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
ML_ARTIFACTS_DIR = ARTIFACTS_DIR / "ml"
DL_ARTIFACTS_DIR = ARTIFACTS_DIR / "dl"

REPORTS_DIR = PROJECT_ROOT / "reports"
ML_REPORTS_DIR = REPORTS_DIR / "ml"
DL_REPORTS_DIR = REPORTS_DIR / "dl"

ML_FIGURES_DIR = ML_REPORTS_DIR / "figures"
ML_TABLES_DIR = ML_REPORTS_DIR / "tables"
DL_TABLES_DIR = DL_REPORTS_DIR / "tables"
